import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const nunitoSans = localFont({
  src: [
    { path: "./assets/fonts/Nunito_Sans/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf", style: "normal" },
    { path: "./assets/fonts/Nunito_Sans/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf", style: "italic" },
  ],
  variable: "--font-nunito-sans",
  display: "swap",
});

const nunito = localFont({
  src: [
    { path: "./assets/fonts/Nunito/Nunito-VariableFont_wght.ttf", style: "normal" },
    { path: "./assets/fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf", style: "italic" },
  ],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Healthy Recipes Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${nunitoSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
